#!/bin/bash

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

set -eu
#set -x

echo_color()
{
        echo -e "\e[1m\e[40;$2m$1\e[0m"
}

echo_error()
{
        echo_color "$1" "31"
        exit 1
}

echo_warning()
{
        echo_color "$1" "33"
        sleep 5
}

if [[ "$(id -u)" != "0" ]]; then
        echo_error "Error: must run with root"
fi

# 全局变量
DEVICE_CONFIG_LIST=$(find /etc/sysconfig/network-scripts -name "ifcfg-enp*" -type f | xargs)

# 检测网卡驱动
if ( ! dmesg | grep -in eth &> /dev/null ); then
        echo_error "Error: the nic driver does not exist"
fi

# 检测配置文件
if [[ -z "$DEVICE_CONFIG_LIST" ]]; then
        echo_error "Error: ifcfg-enp* not found"
fi

# 配置网络
for DEVICE_CONFIG in ${DEVICE_CONFIG_LIST}; do
        
        sed -i "/^BOOTPROTO=/d" ${DEVICE_CONFIG}
        sed -i "/^ONBOOT=/d"    ${DEVICE_CONFIG}
        sed -i "/^IPADDR=/d"    ${DEVICE_CONFIG}
        sed -i "/^PREFIX=/d"    ${DEVICE_CONFIG}
        sed -i "/^GATEWAY=/d"   ${DEVICE_CONFIG}
        sed -i "/^DNS[0-9]*=/d" ${DEVICE_CONFIG}
        sed -i "/^$/d"          ${DEVICE_CONFIG}
        
cat >> ${DEVICE_CONFIG} <<-"EOF"
BOOTPROTO=static
ONBOOT=yes
IPADDR=192.168.8.10
PREFIX=24
GATEWAY=192.168.8.2
DNS1=114.114.114.114
EOF

done

# 重启网络
systemctl restart network

# 禁用 SELinux
sed -i "s/^SELINUX=enforcing/SELINUX=disabled/g"  /etc/selinux/config
sed -i "s/^SELINUX=permissive/SELINUX=disabled/g" /etc/selinux/config

# 下载 quenong
curl -sS https://raw.githubusercontent.com/quefei/quenong/master/install.sh | bash

# 重启服务器
shutdown -r +1
